from subprocess import check_output
env = Environment()
env.Append(CXXFLAGS=["-std=c++17", "-g"], CPPPATH=["include"], LIBS=["rt", "pthread"])

test_lib = check_output(["locate", "boost_unit_test_framework.a"]).rstrip()
test_lib = File(test_lib.decode())

env.Program("main_server", ["main_server.cpp", "src/ProxyBase.cpp", "src/ServerProxyObject.cpp", "src/DynamicArray.cpp"])
env.Program("main_client",["main_client.cpp", "src/ProxyBase.cpp", "src/ClientProxyObject.cpp"])
env.Program("test", ["DynamicArrayProxyTest.cpp", "src/ProxyBase.cpp", "src/ClientProxyObject.cpp", "src/ServerProxyObject.cpp", "src/DynamicArray.cpp"], LIBS=[test_lib, "tbb", "$LIBS"])