import os.path as path

current_dir = path.dirname(".")

opencv_path = path.join(current_dir, "installation/OpenCV-master")
opencv_includes = path.join(opencv_path, "include/opencv4")
opencv_libs = path.join(opencv_path, "lib")

env = Environment()
env.Append(CXXFLAGS=["-g"], CPPPATH=[opencv_includes], LIBPATH=[opencv_libs])

env.Program("brightness", ["brightness.cpp"], LIBS=["opencv_core", "opencv_imgproc", "opencv_highgui", "opencv_imgcodecs"])
