import os.path as path

current_dir = path.dirname(".")

opencv_path = path.join(current_dir, "installation/OpenCV-master")
opencv_includes = path.join(opencv_path, "include/opencv4")
opencv_libs = path.join(opencv_path, "lib")

env = Environment()
env.Append(CXXFLAGS=["-g", "-std=c++17"], CPPPATH=[opencv_includes], LIBPATH=[opencv_libs], LIBS=["pthread"])
try:
    env.ParseConfig("pkg-config --cflags --libs opencv4")
except:
    pass

env.Program("brightness", ["brightness.cpp"], LIBS=["opencv_core", "opencv_imgproc", "opencv_highgui", "opencv_imgcodecs", "tbb" , "$LIBS"])
