from SCons.Environment import Environment
# This is a comment
env = Environment()
env.Append(CCFLAGS=['-g', "-std=c++17"])
env.Append(LIBS=['pthread', 'tbb'])
env.ParseConfig("pkg-config --cflags --libs opencv4")
env.Program(target="main", source=["main.cpp"])
