from SCons.Environment import Environment

env = Environment()   # Create an environmnet
env.Append(CCFLAGS = ['-g'])
env.Append(LIBS=['librt', 'pthread'])
env.Append(CPPPATH=['include'])
env.Program(target = "server", source = ["src/server.cpp", "src/DynamicStringArray.cpp", "src/common.cpp"], LIBS= ["librt", "pthread"])
env.Program(target = "client", source = ["src/client.cpp", "src/common.cpp"], LIBS= ["librt", "pthread"])
env.Program(target = "test", source = ["src/test.cpp", "src/DynamicStringArray.cpp"], LIBS = ["boost_unit_test_framework", "librt", "pthread"] )
