from SCons.Environment import Environment

env = Environment()   
env.Append(CCFLAGS = ['-g'])
env.Append(LIBS=['librt', 'pthread'])

env.Program(target = "server", source = ["server.cpp", "DynamicStringArray.cpp"], LIBS= ["librt", "pthread"])
env.Program(target = "client", source = ["client.cpp"], LIBS= ["librt", "pthread"])
env.Program(target = "test", source = ["IPC_BoostTest.cpp", "DynamicStringArray.o"], LIBS= ["boost_unit_test_framework", "librt", "pthread"])

