env = Environment()   
env.Append(CPPFlags=['-g', '-fprofile-arcs', '-ftest-coverage'])
env.Program(target = "main", source = ["main.cpp","DynamicStringArray.cpp"], LIBS=['gcov'])
env.Program(target = "test", source = ["test.cpp", 'test.o'],LIBS=['gcov', 'boost_unit_test_framework'])
